version: '3'
services:
  frida:
    build: .
    container_name: frida
    restart: always
    tty: true
    environment:
      - tag=16.4.8
      # - archs=["arm", "arm64", "x86", "x86_64"]
      - archs=["arm64"]
    working_dir: /app
    volumes:
      - .:/app
